import { FamilyProfile, TripPlan } from '../types/travel';
import { generateAIItinerary, getEmergencyTriage, getWeatherAlternatives } from './aiEngines';
import { MOCK_NOTICE } from './storage';

/**
 * Client-side browser file downloader using Blob
 */
export function triggerFileDownload(filename: string, content: string, mimeType: string = 'text/plain;charset=utf-8'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Formats a clean, readable Markdown Itinerary and Offline Guide
 */
export function createMarkdownItinerary(trip: TripPlan | null, profile: FamilyProfile | null): string {
  const effectiveTrip = trip || {
    id: 'trip-current',
    destination: 'Kyoto & Nara, Japan',
    startDate: '2026-10-15',
    endDate: '2026-10-20',
    budgetLevel: 'Moderate',
  };

  const itinerary = generateAIItinerary(effectiveTrip, profile);
  const familyName = profile?.familyName || 'Family Travel Party';
  const members = profile?.members || [];
  const primaryPace = members[0]?.pace || 'Slow/Relaxed';

  let md = `# ${effectiveTrip.destination} — Trip Pilot Offline Travel Dossier\n`;
  md += `**Party:** ${familyName} (${members.length} Traveler${members.length === 1 ? '' : 's'})\n`;
  md += `**Travel Dates:** ${effectiveTrip.startDate} to ${effectiveTrip.endDate} · **Budget:** ${effectiveTrip.budgetLevel}\n`;
  md += `**Generated By:** Trip Pilot AI Assistant\n`;
  md += `**Notice:** ${MOCK_NOTICE}\n\n`;

  md += `## 1. Pacing & Dietary Directives Enforced\n`;
  md += `- **Governing Pace:** ${primaryPace}\n`;
  md += `- **Pace Buffer Rationale:** ${itinerary.appliedConstraints.paceExplanation}\n`;
  md += `- **Allergen Shield:** ${itinerary.appliedConstraints.dietaryFilters.join(', ') || 'Standard clean kitchen guidelines'}\n`;
  if (itinerary.appliedConstraints.familyConsiderations.length > 0) {
    md += `- **Special Accommodations:**\n`;
    itinerary.appliedConstraints.familyConsiderations.forEach((c) => {
      md += `  * ${c}\n`;
    });
  }
  md += `\n`;

  md += `## 2. Traveler Roster\n`;
  members.forEach((m, i) => {
    md += `### ${i + 1}. ${m.name} (${m.role})\n`;
    md += `- **Dietary Restrictions:** ${m.dietary.join(', ') || 'None'}\n`;
    md += `- **Pace:** ${m.pace}\n`;
    md += `- **Interests:** ${m.interests.join(', ') || 'General'}\n`;
    if (m.customPreferences.length > 0) {
      md += `- **Personal Notes:** ${m.customPreferences.join(' · ')}\n`;
    }
    md += `\n`;
  });

  md += `## 3. Daily Itinerary & Time Management\n`;
  itinerary.days.forEach((day) => {
    md += `### Day ${day.dayNumber}: ${day.theme} (${day.dateStr})\n\n`;
    day.activities.forEach((act) => {
      md += `#### [${act.time}] ${act.title}\n`;
      md += `- **Category:** ${act.category} | **Location:** ${act.location} | **Estimated Duration:** ${act.estimatedDuration}\n`;
      md += `- **Overview:** ${act.description}\n`;
      md += `- **Pace Note:** ${act.paceNote}\n`;
      if (act.dietaryNote) {
        md += `- **Dietary Note:** ⚠️ ${act.dietaryNote}\n`;
      }
      md += `\n`;
    });
  });

  md += `## 4. Emergency Contacts & Hotline Quick-Reference\n`;
  md += `- **Local Emergency Ambulance:** 119 (Japan) / 911 (US/CA) / 112 (EU)\n`;
  md += `- **24/7 Multilingual Emergency Interpretation:** 0570-000-911\n`;
  md += `- **Health & Medical Consultation Hotline:** +81-75-681-5580\n\n`;

  md += `---\n*Exported from Trip Pilot. Save this document to your mobile device for zero-data offline travel access.*\n`;
  return md;
}

/**
 * Creates structured JSON file for traveler profile
 */
export function createProfileJson(profile: FamilyProfile | null): string {
  const exportPayload = {
    exportedAt: new Date().toISOString(),
    system: 'Trip Pilot AI Travel Assistant',
    disclaimer: MOCK_NOTICE,
    profile: profile || { message: 'No custom profile configured; default traveler slate.' },
  };
  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Creates an emergency medical triage and bilingual card text file
 */
export function createEmergencyCardText(profile: FamilyProfile | null): string {
  const feverTriage = getEmergencyTriage('child_fever');
  const allergyTriage = getEmergencyTriage('allergic_reaction');
  const medicationTriage = getEmergencyTriage('lost_medication');

  const members = profile?.members || [];
  const allAllergies = Array.from(new Set(members.flatMap((m) => m.dietary)));

  let txt = `========================================================\n`;
  txt += ` TRIP PILOT: EMERGENCY MEDICAL TRIAGE & BILINGUAL CARDS\n`;
  txt += ` ${MOCK_NOTICE}\n`;
  txt += `========================================================\n\n`;

  txt += `ACTIVE FAMILY PARTY: ${profile?.familyName || 'Travel Party'}\n`;
  txt += `CRITICAL ALLERGIES ON RECORD: ${allAllergies.join(', ') || 'None recorded'}\n\n`;

  txt += `--------------------------------------------------------\n`;
  txt += ` CARD 1: PEDIATRIC EMERGENCY & SUDDEN HIGH FEVER\n`;
  txt += `--------------------------------------------------------\n`;
  txt += `JAPANESE (Show to Driver / Hotel Front Desk):\n`;
  txt += `${feverTriage.bilingualCard.localized}\n\n`;
  txt += `PHONETIC:\n"${feverTriage.bilingualCard.phonetic}"\n\n`;
  txt += `ENGLISH MEANING:\n"${feverTriage.bilingualCard.english}"\n\n`;

  txt += `--------------------------------------------------------\n`;
  txt += ` CARD 2: SEVERE ALLERGIC REACTION / ANAPHYLAXIS\n`;
  txt += `--------------------------------------------------------\n`;
  txt += `JAPANESE (Show to First Responders):\n`;
  txt += `${allergyTriage.bilingualCard.localized}\n\n`;
  txt += `PHONETIC:\n"${allergyTriage.bilingualCard.phonetic}"\n\n`;
  txt += `ENGLISH MEANING:\n"${allergyTriage.bilingualCard.english}"\n\n`;

  txt += `--------------------------------------------------------\n`;
  txt += ` CARD 3: LOST DAILY PRESCRIPTION MEDICATION\n`;
  txt += `--------------------------------------------------------\n`;
  txt += `JAPANESE (Show to Clinic Receptionist):\n`;
  txt += `${medicationTriage.bilingualCard.localized}\n\n`;
  txt += `PHONETIC:\n"${medicationTriage.bilingualCard.phonetic}"\n\n`;
  txt += `ENGLISH MEANING:\n"${medicationTriage.bilingualCard.english}"\n\n`;

  txt += `--------------------------------------------------------\n`;
  txt += ` EMERGENCY HOTLINES DIRECTORY\n`;
  txt += `--------------------------------------------------------\n`;
  feverTriage.localContacts.forEach((c) => {
    txt += `* ${c.name}: ${c.number} (${c.notes})\n`;
  });
  txt += `\n`;

  return txt;
}

/**
 * Creates a complete full-state bundle JSON
 */
export function createFullTripBundleJson(profile: FamilyProfile | null, trip: TripPlan | null): string {
  const bundle = {
    app: 'Trip Pilot',
    version: '1.0-MVP',
    exportTimestamp: new Date().toISOString(),
    legalDisclaimer: MOCK_NOTICE,
    activeProfile: profile,
    activeTrip: trip,
    weatherContingencies: {
      heavyRain: getWeatherAlternatives('Heavy Rain', profile),
      severeHeat: getWeatherAlternatives('Severe Heat Wave', profile),
    },
    emergencyTriageCards: {
      fever: getEmergencyTriage('child_fever'),
      lostMedication: getEmergencyTriage('lost_medication'),
      allergy: getEmergencyTriage('allergic_reaction'),
    },
  };
  return JSON.stringify(bundle, null, 2);
}
